### 查询服务
GET http://127.0.0.1:9001/imooc/rms-mall-nacos-client/nacos-client/service-instance?serviceId=rms-mall-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIndhbmd5YkBxcS5jb21cIn0iLCJqdGkiOiI3M2ZiMWRkZS02ODM0LTQ4MDItOTA3My04YTMwMTA0YzcyMTUiLCJleHAiOjE2NjY0NTQ0MDB9.cXfOyCXCDT4_Nla7sxm-elwHsVLZwHpyjeRubITcMXO-gxDhNoMCTgibuZf6reKXj72GDrCNf2s8Gt2j4TsGJEM_0-me07QXGrvvjcZFxsK-hfZ-Ik8zrVvTUEc2VU_KapKUytT1JGUPIYr8dfG835kPObAlqhLQAQiqk1BZvVZADkZmRxIYv2Fs2agf2ABds3S7CmHOedwpD1ykhsp1546rvl12oSEJnRpQbySTJCgPzhaSnBaaRjtCCClkz1i1sojp7ppj0y-bP7A_nD-OEwy2Vezk6JxjQMzd_ZMRr2H26PTPHBLSzrM8xoCyFHiikDm4RTGzVvp2Ox3nilBuSg
token: imooc
