### 查询服务
GET http://127.0.0.1:9001/imooc/rms-mall-nacos-client/nacos-client/service-instance?serviceId=rms-mall-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIndhbmd5YkBxcS5jb21cIn0iLCJqdGkiOiJiYTU0MjBjNy0wMTM1LTRhZjYtOGVjYS0wZGUwZmQ5OTI5ZDgiLCJleHAiOjE2NjYxMDg4MDB9.eulJFnRt_I7ycLFhcZVi2wLk8HdWvnHgrXKqBm9j86StFnMl4D4fSFgWGOQoD1dwFgOMT00JhHb77hK1wsxQDMbymIj9iii5m21tNmdRfGY7FbwMh7Bd9M2s3_wkct7xHxcdyQ-z7T_0GgUYRJsT6zpTzBW5bloiltG_V1mqNCxRpvXo9HlztizZg69BaZuVSpoSee-w9g74_cvS9FsZyB9ztu19d6pz-OoByjBbWC0u4F_9TS8zCkWsGpGTReiKiP4MVPVHv44BqAUqJFLsLky7kPRx351tVQDuCNT5mXN0U-Pu4HEOtIV59C8GwvtXJooLAQtsJ5vccF_ax_WkMQ
token: imooc
