### 查询服务
GET http://127.0.0.1:9001/imooc/rms-mall-nacos-client/nacos-client/service-instance?serviceId=rms-mall-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIndhbmd5YkBxcS5jb21cIn0iLCJqdGkiOiJjMWE5MWRmNC0zYjc3LTQ2MjktYjZjNC01M2MwZDYzNDczMzAiLCJleHAiOjE2NjYyODE2MDB9.K2K6WRKIUy3a96CKdxOxMKHDXheZlOaVcc5yglqlGq8Hf5idsJApgT0gE6T13mawrnvafwG0OnI2KHOWX05h8cSfkS25_IXCEFy_Qk-Wyf8pgLCFWQZU4MhIbMqVCzv7WB196fZYunAlr0JaYL2BJRxMr4k2Lu5x2o9y2jTBTkT4Yc1qpfgZEQLM9Ab5s6mszEA36qHFZDlKiT5iT_mVZUbO8aaB-IDhNT5wi5HDeFYkr82C5Q_v7Ic1uwZLWnaZa0wTnFQFr_ouj39itaziUlWtvxaSlmOFCW3n9QMdlVagdaTqpCqeUNGdu5ptEUysrnDgd6eBLSganiS_SKHirA
token: imooc
