### 导入商品
POST http://127.0.0.1:9001/rms-mall/rms-mall-goods-service/async-goods/import-goods
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjExLFwidXNlcm5hbWVcIjpcIkltb29jUWlueWlJbW9vY0BpbW9vYy5jb21cIn0iLCJqdGkiOiIwN2M4ZWQ5YS0xYzkwLTQzNzctYWMwZS00NGMxMmViMGU2NzAiLCJleHAiOjE2NDU4MDQ4MDB9.d24y_xfxdKZDAaGcNjNjkbPsGCLHTIFaHRtXaBZsNgJSRsazokpVQ6HpvBP8u0awN57KQgxM_PMZ52bvtXY7VAWUXkHMR0qvdXvDO_y25Dx7N3ctU1ZXeKDc34UF7Z9HMFq8QhwvIlH5WkS-UOxbqZur360yTqPbiV1NunljQgzpkKFdgRVnr1X_AgfjvmxeC4KTrTliF3ZOlfmn0ARIs3E0zKl8s8OjHzoJg7XIR0wHlD3Yay0Zc_eVyKvQXJH670IYdl5fxw2fZh7gW6C-JM8t9NeC4LTDEdROEi9sfK0LDHexJZw6eQAbP43TcACRhrIfx4lifF-Y2KTsJiDQ3A

[
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 11",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 100000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  },
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 12",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 150000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  },
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 13",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 160000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  }
]


### 查询导入商品状态
GET http://127.0.0.1:9001/rms-mall/rms-mall-goods-service/async-goods/task-info?taskId=f5c1c6ff-4efb-45e5-a8c9-9f3d4515228a
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjExLFwidXNlcm5hbWVcIjpcIkltb29jUWlueWlJbW9vY0BpbW9vYy5jb21cIn0iLCJqdGkiOiIwN2M4ZWQ5YS0xYzkwLTQzNzctYWMwZS00NGMxMmViMGU2NzAiLCJleHAiOjE2NDU4MDQ4MDB9.d24y_xfxdKZDAaGcNjNjkbPsGCLHTIFaHRtXaBZsNgJSRsazokpVQ6HpvBP8u0awN57KQgxM_PMZ52bvtXY7VAWUXkHMR0qvdXvDO_y25Dx7N3ctU1ZXeKDc34UF7Z9HMFq8QhwvIlH5WkS-UOxbqZur360yTqPbiV1NunljQgzpkKFdgRVnr1X_AgfjvmxeC4KTrTliF3ZOlfmn0ARIs3E0zKl8s8OjHzoJg7XIR0wHlD3Yay0Zc_eVyKvQXJH670IYdl5fxw2fZh7gW6C-JM8t9NeC4LTDEdROEi9sfK0LDHexJZw6eQAbP43TcACRhrIfx4lifF-Y2KTsJiDQ3A
